# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ecfd3d7850e698b4d163713195d2f4c64095907b219c16f0c2c9b63062f52e664f2d806e4f1918d5b385e6a77f74a96ab10c7e05843764397a59cf95c505f27

test:
  secret_key_base: d6cd16b888ae62379c961193c43362daa5f23637c6ed7aca0cd134f4fcf15975a1b6309fe2f93356ec38e978ccd16385e8cfa6046afad82e84fb2a1d188e14d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
